services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    user: "1000:1000" # Match the non-root user UID/GID