services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    command: >
      bundle exec jekyll serve --source sitefiles --destination sitefiles/_site --host 0.0.0.0 --port 4000 --livereload
    develop:
      watch:
        - action: sync
          path: ./sitefiles
          target: /app/sitefiles
          ignore:
            - sitefiles/_site/
            - sitefiles/.jekyll-cache/