# Site settings
title: Modern Engineering for Lasting Impact!
description: Accelerate success with Cloud Engineering, DevOps & Agile.
baseurl: "" # Set to "/repository-name" if hosted in a subdirectory
url: "https://impacteng.com.au"

social:
  twitter: https://x.com/impactengx
  linkedin: https://www.linkedin.com/company/impactengx
  github: https://github.com/ImpactEng
  email: hi@impacteng.com.au


# Build settings
markdown: kramdown
theme: minima
plugins:
  - github-pages
#  - jekyll-feed
#  - jekyll-seo-tag


# GitHub Pages settings
#remote_theme: jekyll/minima
#github:
#  is_project_page: false

# Security settings
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - vendor/
  - scripts/
  - .github/
  - README.md
  - .gitignore
  - ../ # Prevent including parent directory

# Output
destination: ./_site
